### ISSUE TITLE
macOS Build Fails with Unresolved References and AppImage Target Format

### ISSUE THREAD

**Issue by Tarek-Bohdima** [OShane-McKenzie/YATDO#1]
## Issue: Difficulties Building and Running on macOS

**Describe the bug**

I'm having trouble building and running the YATDO application on macOS using IntelliJ IDEA. I've encountered the following issues:

* **Unresolved references:**  IntelliJ IDEA reports "Unresolved reference: macosx64" and "Unresolved reference: iconFile" in the `build.gradle.kts` file.
* **Unexpected target format:**  Even after correcting the `targetFormats` to include `TargetFormat.Dmg` and `TargetFormat.Pkg`, I still get the error "Unexpected target format for MacOS: AppImage."

**To Reproduce**

1. Clone the YATDO repository.
2. Open the project in IntelliJ IDEA.
3. Try to build and run the application using the default "desktop" configuration.

**Expected behavior**

The application should build successfully and run without errors on macOS.

**Environment:**

* **OS:** macOS [Specify macOS version, e.g., macOS Ventura 13.5]
* **IDE:** IntelliJ IDEA 2024.2.4 (Community Edition)
* **Kotlin plugin version:** 242.23726.103-IJ
* **Gradle version:** bundled 242.23726.103

**Additional context**

* I have tried updating the Kotlin plugin and IntelliJ IDEA to the latest versions.
* I have invalidated caches and restarted the IDE.
* I have ensured that the `build.gradle.kts` file is correctly configured for macOS targets (see screenshot).

Please provide any assistance or guidance on resolving these issues.

**Comment by OShane-McKenzie** [comment]
Have you tried removing TargetFormat.AppImage ?

**Comment by Tarek-Bohdima** [comment]
Yes , i tried , didn't work.

**Comment by OShane-McKenzie** [comment]
YATDO is specifically designed to target Linux desktops (see readme), and it uses Linux-specific libraries.

**Comment by Tarek-Bohdima** [comment]
oh, Thanks for Clarification
